name: measurement
description: utility for measurements requiring value and unit
version: 0.0.1-readme
homepage: https://github.com/aljorhythm/measurement

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  trotter: ^1.1.1
  tuple: ^1.0.3

dev_dependencies:
  test: ^1.14.1
