name: measurement
description: utility for measurements requiring value and unit
version: 0.0.1-github-action
homepage: https://github.com/aljorhythm/measurement

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.14.1