name: Dart CI - deploy

on:
  push:
    branches: [ integration ]
  pull_request:
    branches: [ integration ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name : test git
      run: |
        git fetch origin master
        git checkout -b master origin/master
        git pull origin integration
        exit
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
        EOF
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Deploy
      run: pub publish -f
    - name: Merge to master
      run: |
        git fetch origin master
        git checkout -b master origin/master
        git pull origin integration
        git push
